spring:
  application:
    name: news-fetcher-service (DEV)

server:
  port: ${SERVER_PORT:8080}

  ai:
    mcp:
      server:
        type: SYNC
        version: 1.0.0
        stdio: true
        capablities:
            resource: true
            prompt: true
            tool: true
            completion: true
        sse-endpoint: ${MCP_SSE_ENDPOINT:http://localhost:8080/mcp/sse}
        sse-message-endpoint: ${MCP_SSE_MESSAGE_ENDPOINT:http://localhost:8080/mcp/sse/message}


  mcp:
    server:
      name: NewsFetcherMCPServer (DEV)
      

#   main:
#     web-application-type: servlet
#     banner-mode: off
# logging:
#   pattern:
#     console: 
    
build:
  info:
    name: News Fetcher Service
    description: A service to fetch news from external APIs
    version: 1.0.0

external-news-api:
    base-url: ${NEWS_API_BASE_URL:https://newsapi.org/v2}
    endpoint:
      top-headlines: ${TOP_HEADLINES_ENDPOINT:top-headlines}
      everything: ${EVERYTHING_ENDPOINT:everything}
      sources: ${SOURCES_ENDPOINT:sources}
    api-key: ${NEWS_API_KEY:}
