spring:
  application:
    name: news-fetcher-service (DEV)

  ai:
    mcp:
      server: 
        name: news-fetcher-service-mcp
        version: 1.0.0

  main:
    banner-mode: off 
  logging:
      file:
        name: news-fetcher-service.log
                
server:
  port: ${SERVER_PORT:8080}
    
build:
  info:
    name: News Fetcher Service
    description: A service to fetch news from external APIs
    version: 1.0.0

external-news-api:
    base-url: ${NEWS_API_BASE_URL:https://newsapi.org/v2}
    endpoint:
      top-headlines: ${TOP_HEADLINES_ENDPOINT:top-headlines}
      everything: ${EVERYTHING_ENDPOINT:everything}
      sources: ${SOURCES_ENDPOINT:sources}
    api-key: ${NEWS_API_KEY:}
